### ISSUE TITLE
Malformed UTF-8

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/whateverable#153]
In some cases we get errors like this:
```
Unhandled exception in code scheduled on thread 20
Malformed UTF-8
```

The source of it seems to be Proc::Async from [``get-output``](https://github.com/perl6/whateverable/blob/8278ed7be531875b5842a1d9ae5157a551dda254/Whateverable.pm6#L99-L127) sub.

Logically, one would want to use ``$proc.stdout(:enc<utf8-c8>)`` to make it work, but it [only corrupts memory](https://irclog.perlgeek.de/perl6-dev/2017-05-24#i_14631150).

So the issue is not in whateverable, as I believe. There's something wrong with rakudo and it has to be rakudobugged, but right now I don't know what exactly.

**Comment by AlexDaniel** [comment]
Again: https://irclog.perlgeek.de/perl6-dev/2017-06-26#i_14787712

**Comment by MasterDuke17** [comment]
Should be fixed with https://github.com/rakudo/rakudo/commit/49f555a2fb.

**Comment by AlexDaniel** [comment]
Probably not.
```
<AlexDaniel> greppable6: kill[^-']
*** greppable6 has quit: Remote host closed the connection
```
```
Unhandled exception in code scheduled on thread 20
Malformed UTF-8
```

**Comment by AlexDaniel** [comment]
link: https://github.com/perl6/whateverable/issues/24

**Comment by AlexDaniel** [comment]
Still present even after [RT #131961](https://rt.perl.org/Ticket/Display.html?id=131961), but this time I don't know if rakudo is at fault.

**Comment by AlexDaniel** [comment]
I think this was resolved in https://github.com/perl6/whateverable/commit/04beb801aba61ee10ba0e0630f406419e8b7c278, tests needed.

**Comment by AlexDaniel** [comment]
FWIW for tests, one of the examples that was failing was:
> greppable6: `\+\+\$[\W\s]`
> No! It wasn't me! It was the one-armed man! Backtrace: https://gist.github.com/afcbfddf27d18f0aa684db062da7da52

I think the problem in that case was with some [weird characters in a module](https://github.com/zoffixznet/perl6-Acme-Anguish/blob/811b72c3266a5c019ee77f541a7858a828008b22/lib/Acme/Anguish.pm6#L24).
